### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by kurodenjiro** [nlpyang/PreSumm#89]
Traceback (most recent call last):
  File "train.py", line 135, in <module>
    test_abs(args, device_id, cp, step)
  File "E:\project\PreSumm\src\train_abstractive.py", line 215, in test_abs
    model = AbsSummarizer(args, device, checkpoint)
  File "E:\project\PreSumm\src\models\model_builder.py", line 212, in __init__
    self.generator = get_generator(self.vocab_size, self.args.dec_hidden_size, device)
  File "E:\project\PreSumm\src\models\model_builder.py", line 111, in get_generator
    generator.to(device)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 381, in to
    return self._apply(convert)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 187, in _apply
    module._apply(fn)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 193, in _apply
    param.data = fn(param.data)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 379, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\torch\cuda\__init__.py", line 161, in _lazy_init
    _check_driver()
  File "C:\Users\Admin\Anaconda3\lib\site-packages\torch\cuda\__init__.py", line 75, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by natshv** [comment]
@kurodenjiro Hi, I guess you hadn't installed the wheel properly, I also had this issue but it was fixed after the proper installation: https://pytorch.org/get-started/previous-versions/
